### ISSUE TITLE
reload! from Rails console throws exception

### ISSUE THREAD

**Issue by blelump** [jeromegn/dry-data-rails#1]
Hi!

Thanks for your contribution and this gem! When running Rails in development environment, I'm getting

```
Loading development environment (Rails 4.2.5)
2.2.0 :001 > reload!
Reloading...
NameError: instance variable @container not defined
```

which I simply monkey–patched with:

```
if Dry::Data.instance_variable_defined?(:@container)
  Dry::Data.remove_instance_variable :@container
end
```

Quite weird, though. Have you experienced similar behaviour? I'm sticked to `dry-data` v0.5.1.

**Comment by jeromegn** [comment]
Thanks! Just pushed 0.1.1 with that code.
