### ISSUE TITLE
 undefined method `visit_String'

### ISSUE THREAD

**Issue by allan-farrell** [jeromegn/dry-data-rails#6]
I'm getting the following error when trying to start the rails server in dev mode while using this gem.

dry-logic-0.2.3/lib/dry/logic/rule_compiler.rb:18:in `visit': undefined method`visit_String' for #Dry::Logic::RuleCompiler:0x000000053c0cf8 (NoMethodError)

I'm running rails 4.2, ruby 2.3.0

**Comment by allan-farrell** [comment]
Looks like I'm using 0.1.2 which is not latest version. Could you update version on rubygems to 0.3.1? Thanks.

**Comment by jeromegn** [comment]
Rubygems has had 0.3.1 for a while.

I just released 0.3.2 which has some changes, but nothing that would cause the error you experienced (I think.)
